[package]
name = "playlist_transit"
version = "0.1.0"
authors = ["Claire Moore <nrmoore@uci.edu>"]

[dependencies]
roxmltree = "0.4.0"
nfd = {version = "0.0.4", optional = true}

[profile.release]
panic = "abort"

[features]
default = ["gui"]

gui = ["nfd"]
